[workspace]
resolver = "2"
members = [
    "adsheader",
    "adsloopfind",
    "cds2seq",
    "demul",
    "demus",
    "desnd",
    "msqsplit",
    "seqrepeat", "sf2panlaw",
    "vabfine", "vabsmp", "vagheader",
]
